FROM kalilinux/kali-rolling:latest
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        build-essential devscripts debhelper \
        fakeroot dpkg-dev git ca-certificates && \
    rm -rf /var/lib/apt/lists/*
ENTRYPOINT ["/bin/bash"]
