#!/bin/sh
set -e

PREFIX="/opt/cloud-apt-hello-0.2.0"

case "$1" in
    configure)
        ln -sf "$PREFIX/bin/cloud-apt-hello" /usr/local/bin/cloud-apt-hello
        echo "cloud-apt-hello: installed /usr/local/bin/cloud-apt-hello -> $PREFIX/bin/cloud-apt-hello"
        ;;
esac

exit 0


